version: '3.8'
services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.2
    container_name: wazuh-manager
    restart: always
    ports:
      - "1514:1514/tcp" # Agent connection
      - "1515:1515/tcp" # Agent registration
      - "514:514/udp"   # Syslog
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
    volumes:
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs

volumes:
  wazuh_etc:
  wazuh_logs:
